  version: "3.8"

  services:
    app:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      container_name: kado-api
      volumes:
        - app_public:/var/www/public
        - ./.env:/var/www/.env
      env_file:
        - .env
      depends_on:
        - mysql
      networks:
        - kado-network
      restart: unless-stopped
      healthcheck:
          test: ["CMD", "php", "-v"]
          interval: 5s
          timeout: 2s
          retries: 10

    nginx:
      image: nginx:alpine
      container_name: kado-nginx
      ports:
        - "8081:80"
        - "8444:443"
      volumes:
        - app_public:/var/www/public:ro
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        app:
          condition: service_healthy
      networks:
        - kado-network
      restart: unless-stopped

    mysql:
      image: mysql:8.0
      container_name: kado-db
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      ports:
        - "3307:3306"
      volumes:
        - mysql_data_fillament:/var/lib/mysql
      networks:
        - kado-network
      restart: unless-stopped

  volumes:
    mysql_data_fillament:
    app_public:

  networks:
    kado-network:
      driver: bridge