version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: fillament-app-dev
    user: "${UID}:${GID}"
    volumes:
      - ./:/var/www       # monta o projeto todo
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file:
      - .env
    depends_on:
      - mysql
      - mailhog
    ports:
      - "9000:9000"       # PHP-FPM dev
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: fillament-nginx-dev
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:ro
      - ./docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: fillament-db-dev
    environment:
      MYSQL_DATABASE: laravel_dev
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_fillament_dev:/var/lib/mysql
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog
    container_name: fillament-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

volumes:
  mysql_data_fillament_dev:
